Historie editace
JaLe29/react-adminer pull request #31
Opened 2022-10-22 22:45 UTC by mastnytomas

2022-10-22 23:20 UTC, mastnytomas commented
![image](https://user-images.githubusercontent.com/109352229/197365829-e7c29285-b072-4fcd-9424-c25b3e57eae8.png)
Oprava InputNumber komponenty
(Nešlo editovat data typu: number)

2022-10-23 07:18 UTC, JaLe29 requested changes

2022-10-23 07:18 UTC, JaLe29 commented on packages/react-adminer/src/components/Edit.tsx
> +	const { Panel } = Collapse;
Tohle hoď mimo komponentu, jen se "rozbaluje" knihovna, takže to nemusíš dělat při každém renderu.

2022-10-23 07:18 UTC, JaLe29 commented on packages/react-adminer/src/components/Edit.tsx
> +					<Collapse accordion>
Tohle musí být určitě komponenta - nový soubor a oddělený kód..

2022-10-23 07:18 UTC, JaLe29 commented on packages/react-adminer/src/components/Edit.tsx
> +		const summaryChangedData: any[] = [];
Bez any, typ znáš, vytváříš ho.

2022-10-23 07:18 UTC, JaLe29 commented on packages/react-adminer/src/components/Edit.tsx
> +		changedKeys?.map((key: string) =>
Mapa ti vrací data, takže nepotřebuješ nic pushovat.

```
		return changedKeys?.map((key: string) => {
			return ({
				field: getColumnTitle(getFieldByName(config, key)),
				original: original[key],
				changed: state[key],
			})
		});
```

2022-10-23 08:59 UTC, merged

2022-10-23 08:59 UTC, JaLe29 commented
No vidis, to je parada ted.